Feature/sdktp 76 3d models revisions api v1
cognitedata/cdf-sdk-java pull request #100
Opened 2022-01-03 20:38 UTC by digaomilleniun

2022-01-04 18:50 UTC, cognite-ornellas commented on src/test/java/com/cognite/client/ThreeDAvailableOutputsTest.java
> +    void retriverThreeDAvailableOutputs() throws MalformedURLException {
think you meant retrieve instead of retrieve**r**

2022-01-04 18:50 UTC, cognite-ornellas commented on src/test/java/com/cognite/client/ThreeDAvailableOutputsTest.java
> +            String loggingPrefix = "UnitTest - retriverThreeDAvailableOutputs() -";
same here

2022-01-04 18:52 UTC, cognite-ornellas commented on src/main/java/com/cognite/client/ThreeDAvailableOutputs.java
> +        List<CompletableFuture<ResponseItems<String>>> resultFutures = new ArrayList<>();
think you can just call tdReader.getItemsAsync(addAuthInfo(request)) and join from that response as you haven't a list here

2022-01-04 18:55 UTC, cognite-ornellas commented on src/main/java/com/cognite/client/ThreeDAvailableOutputs.java
> +    private ThreeDAvailableOutput parseThreeDAvailableOutputs(String json) {
maybe this method is not needed as your already throwing Exception at the method's signature

2022-01-04 18:57 UTC, cognite-ornellas commented on src/main/java/com/cognite/client/ThreeDModelsRevisions.java
> +    private ThreeDModelRevision parseThreeDModelRevision(String json) {
Same of the previows comment here. The parent method is already throwing Exception. You can check the other parsers in this class.

2022-01-04 18:58 UTC, cognite-ornellas commented on src/main/java/com/cognite/client/servicesV1/request/ThreeDAvailableOutputsRequestProvider.java
> +        //ImmutableList<Class> validClasses = ImmutableList.of(String.class, Integer.class, Long.class);
think you forgot removing this line here

2022-01-04 19:00 UTC, cognite-ornellas approved these changes
I've left some comments, but they are about small improvements only

2022-01-06 20:13 UTC, kjetilh33 requested changes
Excellent draft. You are starting to get very familiar with the structure of the SDK.

2022-01-06 20:13 UTC, kjetilh33 commented on src/main/proto/three_d_model.proto
> +message ThreeDAvailableOutput {
Maybe a bit cosmetic... but one thought on naming: Should we just call it "ThreeDOutput"?

When the client calls the SDK/API endpoint "get available outputs", the result is a list of "ThreeDOutput(s)". Does that make sense?

2022-01-06 21:28 UTC, digaomilleniun commented on src/main/proto/three_d_model.proto
> +message ThreeDAvailableOutput {
Yes I totally agree. I'll fix them.

2022-01-11 15:55 UTC, kjetilh33 approved these changes

2022-01-25 02:39 UTC, closed without merging

2022-01-25 02:41 UTC, digaomilleniun commented
This features was merge in another branch