Feature/sdktp 138 doc 3d model revisions
cognitedata/cdf-sdk-java pull request #115
Opened 2022-01-28 15:52 UTC by digaomilleniun

2022-02-01 12:36 UTC, cognite-ornellas approved these changes

2022-02-01 12:55 UTC, kjetilh33 requested changes

2022-02-01 12:55 UTC, kjetilh33 commented on src/main/java/com/cognite/client/ThreeDOutputs.java
>                  .withRootParameter("modelId", String.valueOf(modelId))
I think you can just pass the Long value directly without "stringifying" it. The RequestBuilder will parse the type correctly to string path elements.

2022-02-01 12:55 UTC, kjetilh33 commented on src/main/java/com/cognite/client/ThreeDRevisionLogs.java
> -                .withRootParameter("modelId", String.valueOf(modelId))
I think you can just pass the Long value directly without "stringifying" it. The RequestBuilder will parse the type correctly to string path elements.

2022-02-02 07:56 UTC, kjetilh33 approved these changes

2022-02-03 13:15 UTC, merged