Feature/sdktp 138 doc 3d model revisions
cognitedata/cdf-sdk-java pull request #122
Opened 2022-02-07 17:31 UTC by digaomilleniun

Added docs for 3d models

2022-02-11 07:56 UTC, kjetilh33 requested changes

2022-02-11 07:56 UTC, kjetilh33 commented on docs/threeD.md
> +  - Cursor for paging through results.
Should we leave this parameter ("cursor") out of the doc? The SDK will handle the cursor under the hood so it should not be set by the user/client in the request object.

2022-02-11 07:56 UTC, kjetilh33 commented on docs/threeD.md
> +    .withRootParameter("cursor", "")
Should we leave this parameter ("cursor") out of the doc? The SDK will handle the cursor under the hood so it should not be set by the user/client in the request object.

2022-02-11 07:56 UTC, kjetilh33 commented on docs/threeD.md
> +  - Limits the number of results to be returned. The maximum results returned by the server is 1000 even if you specify a higher limit.
The limit parameter will set the batch size returned. Since the SDK will iterate through all the results pages (from the api), the client will get the complete results set no matter what the "limit" parameter is set at.

Also, the SDK should set a reasonable "limit" by default so that the client should not need to set it manually.

2022-02-11 14:32 UTC, digaomilleniun commented on docs/threeD.md
> +  - Cursor for paging through results.
OK I removed the cursor filter option

2022-02-11 14:33 UTC, digaomilleniun commented on docs/threeD.md
> +  - Limits the number of results to be returned. The maximum results returned by the server is 1000 even if you specify a higher limit.
OK I removed the limit filter option

2022-02-15 18:25 UTC, kjetilh33 approved these changes

2022-02-16 13:14 UTC, merged