added raw docs md
cognitedata/cdf-sdk-java pull request #124
Opened 2022-02-09 01:20 UTC by digaomilleniun

MD docs for raw

2022-02-09 12:43 UTC, kjetilh33 reviewed
Overall, really nice work on the documentation!

I have added a few comments. They are mostly on details like certain api parameters that the SDK tries to handle on the behalf of the client/user.

2022-02-09 12:43 UTC, kjetilh33 commented on docs/raw.md
> +
The "limit" and "cursor" parameters are advanced parameters that the average SDK client should not need to worry about. The SDK will automatically handle the results set iteration so that the client just gets the iterator back. 

Maybe we should add that to the documentation? I.e. that a client typically should not set any "cursor" options when operating raw (and other endpoints).

2022-02-09 12:43 UTC, kjetilh33 commented on docs/raw.md
> +
Correct information when looking at the CDF api. But the SDK should "hide" this complexity from the client. I.e. the SDK will just chunk the input into the max 1k batch size and send multiple requests under the hood.

2022-02-09 12:43 UTC, kjetilh33 commented on docs/raw.md
> +
Same as above. In particular with respect to the cursor parameter. We may want to hide this or make it clear to the client/user that they should leave the handling of "cursor" to the SDK.

2022-02-09 12:43 UTC, kjetilh33 commented on docs/raw.md
> +
Setting the number of cursors is an advanced setting. The SDK will typically try and handle this for you.

2022-02-09 12:43 UTC, kjetilh33 commented on docs/raw.md
> +
Yes, the max row batch size is correct. But the SDK will handle chunking and batching on behalf of the client so they can "just post" large set of rows and the SDK will handle the rest.

2022-02-10 10:26 UTC, kjetilh33 requested changes

2022-02-10 10:26 UTC, kjetilh33 commented on docs/raw.md
> +
Could we add a sentence that explains to the user that the SDK will normally handle parallelization for you, and that custom parallelization (via cursors) is an advanced use case?

2022-02-10 15:11 UTC, kjetilh33 commented on docs/raw.md
> +
Yes, good point. The SDK offers two "categories" of use: the regular/standard case where all the parallelization is handled automatically. This would be the case for almost all `list()` methods. 

Then we have the "advanced" category which is for clients like distributed frameworks. For these, we have the one, specialized "list(param1, param2, param3, String... cursors)" which offers custom control of the cursors. So it may be worth mentioning this explicitly.

In any case, we don't use the cursor parameter in the Request object.

2022-02-11 00:47 UTC, digaomilleniun commented on docs/raw.md
> +
OK. I made a sketch, could you check if I understand the idea?

2022-02-15 14:59 UTC, kjetilh33 approved these changes

2022-02-15 15:22 UTC, merged