Added Transformations
cognitedata/cdf-sdk-java pull request #149
Opened 2022-04-21 22:19 UTC by digaomilleniun

2022-04-23 10:47 UTC, kjetilh33 requested changes
Great start to a fairly complex API endpoint. There are two items I'd like us to double check:
1. Upsert logic can leverage the ItemUpsert helper class (please check Events.upsert() for reference).
2. I suspect we can simplify the proto specification for the DTOs. 

Apart from these two I just added some minor, cosmetic comments. 

I'll be happy to run through the items in a VC for discussion. Would love to hear your thoughts as well as these are design considerations (and not binary right/wrong) where we need to evaluate the best options.

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/java/com/cognite/client/Transformations.java
> +    public List<Transformation> upsert(List<Transformation> transformations) throws Exception {
You can probably leverage the UpsertItems class which will handle the upsert logic (with conflict detection and all) for you. It seems that the Transformations endpoint has similar patter as Event. 

Please have a look at Events.upsert(List<Event> events) for inspiration. I will be more than happy to walk you through the pattern.

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/java/com/cognite/client/servicesV1/ConnectorServiceV1.java
> +        LOG.debug(loggingPrefix + "Initiating delete Transformations service.");
Probably don't need this log entry any more. I have started removing it from the other readers/writers in ConnectorServiceV1 as they don't offer any real debugging value. 

These log entries were very useful at the early days of the SDK development, but I hardly get any value out of them nowadays.

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  optional bool hasSourceApiKey = 21;
Can be removed. Will be automatically handled by "optional string sourceApiKey".

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  optional bool hasDestinationApiKey = 22;
Can be removed. Will be automatically handled by "optional string destinationApiKey".

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  optional bool hasSourceOidcCredentials = 23;
Can be removed

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  optional bool hasDestinationOidcCredentials = 24;
can be removed

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  optional DataSource1 dataSource1 = 4;
How about we just have a single field "destination" with type "destination"?

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  optional RawDataSource rawDataSource = 5;
How about we just have a single field "destination" with type "destination"?

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  optional SequenceRowDataSource sequenceRowDataSource = 6;
How about we just have a single field "destination" with type "destination"?

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +    optional DataSource1 dataSource1 = 7;
How about we just have a single field "destination" with type "destination"?

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +    optional RawDataSource rawDataSource = 8;
How about we just have a single field "destination" with type "destination"?

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +    optional SequenceRowDataSource sequenceRowDataSource = 9;
How about we just have a single field "destination" with type "destination"?

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  message JobRead {
Should we just call it "Job", or would that conflict with some other naming?

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  message Owner {
Does "owner" need to be a type/message or can it just be a string?

2022-04-23 10:47 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  message DataSource1 {
How about refactoring the various data source types (DataSource1, RawDataSource, etc.) to a single "Destination" type. 

The Destination type has one enum that captures all destinations (including raw and sequence row) + externalId, db and table (all optional).

2022-04-25 22:21 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  optional bool hasSourceApiKey = 21;
I put these fields because we only have the destinationApiKey field only in the upinsert, but in the return and in the list and retrieve only the has* fields are returned

2022-04-25 22:21 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  optional bool hasDestinationApiKey = 22;
I put these fields because we only have the destinationApiKey field only in the upinsert, but in the return and in the list and retrieve only the has* fields are returned

2022-04-26 12:23 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  message Owner {
The return result of endpoint retrieve(byids) is:

"owner": { "user": "8wmra5ppo_i13zp7bczhdnq5 kpela02nbdyein vwi" }

Because of this return I put it inside an object. Perhaps the future may come a few more fields.

2022-04-27 01:34 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  message DataSource1 {
I changed this object. Please tell me if I understood correctly.

2022-04-28 08:34 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  message Owner {
Good point. I just got confused by the API documentation where "owner" is defined as a string field. Do you know which one is correct?

2022-04-28 08:44 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  optional bool hasSourceApiKey = 21;
I understand. Here is where it would be great to get your opinions. If we just have the "optional string source_api_key" proto definition, then the generated code will offer both: 1) "set/getSourceApiKey()" and 2) "hasSourceApiKey()". I.e. all "optional" proto fields will automatically be accompanied by a boolean "hasXXX()" which indicates if the field is populated at all. 

There may be a bit of a confusion for the user if we have a separate field named "hasXXX" in addition?

The way that we could handle this with a sigle "optional string xxx" in the case of the API returning "hasXXX" is a follows:
- if the API returns "false" in a "hasXXX" field, then we don't touch any of the corresponding optional fields in the proto object. In this case, the client will receive "false" when calling the proto-object's "hasXXX()" methods. 
- if the API returns "true" in a "hasXXX" field, then we set the proto-object's corresponding field (example "setSourceApiKey(String value)) to a default, invalid value. Say "" (the empty string) for "optional String" field and "-1" (minus one) for "optional int" fields. When the client calls "hasXXX" on the proto-object, the method will return "true". 

The fact that we actually populate the underlying field (ex sourceApiKey) with an invalid value must be clearly documented so we don't mislead the user.

2022-04-28 08:58 UTC, kjetilh33 requested changes

2022-04-28 08:58 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +    string tokenUri = 4;
Can we use underscore_separated_names for the field name for consistency?

2022-04-28 08:58 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +    enum DataSource1Type {
Just name it "DataSourceType" (without the 1 as a part of the name)?

2022-04-28 08:58 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +    }
We may not need this enum. Even though the API defines a set of "object structures" to describe the API object, I don't think we need it in the proto

2022-04-28 08:58 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  }
Can be removed

2022-04-28 08:58 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  }
can be removed

2022-04-28 08:58 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  }
Can be removed

2022-04-28 08:58 UTC, kjetilh33 commented on src/main/proto/transformation.proto
> +  }
How about refactoring the Destination message type to the following:
message Destination {
  enum DataSourceType {
ASSETS = 0;
      TIMESERIES = 1;
      ASSET_HIERARCHY = 2;
      EVENTS = 3;
      DATAPOINTS = 4;
      STRING_DATAPOINTS = 5;
      SEQUENCES = 6;
      SEQUENCE_ROWS = 7;
      FILES = 8;
      LABELS = 9;
      RELATIONSHIPS = 10;
      DATA_SETS = 11;
    }

  DataSourceType type = 1;
  optional string database = 2;
  optional string table = 3;
  optional string external_id = 4;

}

Then we use the logic in the TransformationParser to translate that proto object to the various Json data source schemas?

The relationship proto + parser is an example of the pattern.

2022-05-02 15:32 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  optional bool hasSourceApiKey = 21;
I understood your point. In my opinion, we can stop manipulating these values ​​in the update and replace methods and create a specific method to deal with these fields. Imagine this scenario: The user makes a query by id and just changes the name field and sends an update request. If we put a default value in the source_api_key, destination_api_key, source_oidc_credentials and destination_oidc_credentials objects, we will get an API error 400 because the sourceOidcCredentials object is instantiated and contains empty Strings. What do you think?

2022-05-02 15:50 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  }
I'm using these objects to make it easier to parse objects like this:

mapBuilder.put("destination", Transformation.SequenceRowDataSource.newBuilder()
                        .setType(element.getDestination().getType())
                        .setExternalId(element.getDestination().getExternalId())
                        .build());

As the API expects to receive these objects and if we remove them we would need to create a new Serializer to intercept and write the json as the API expects. There is an example of this in this https://github.com/cognitedata/cdf-sdk-java/blob/main/src/main/java/com/cognite/client/servicesV1/request/ThreeDNodesFilterRequestProvider.java where I use a custom https://github.com/cognitedata/cdf-sdk-java/blob/main/src/main/java/com/cognite/client/servicesV1/request/serializer/ThreeDNodePropertiesFilterSerializer.java for this conversion activity.

I find it simpler to marter the objects.

2022-05-02 15:51 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  }
I'm using these objects to make it easier to parse objects like this:

mapBuilder.put("destination", Transformation.RawDataSource.newBuilder()
                        .setType(element.getDestination().getType())
                        .setDatabase(element.getDestination().getDatabase())
                        .setTable(element.getDestination().getTable())
                        .build());

As the API expects to receive these objects and if we remove them we would need to create a new Serializer to intercept and write the json as the API expects. There is an example of this in this https://github.com/cognitedata/cdf-sdk-java/blob/main/src/main/java/com/cognite/client/servicesV1/request/ThreeDNodesFilterRequestProvider.java where I use a custom https://github.com/cognitedata/cdf-sdk-java/blob/main/src/main/java/com/cognite/client/servicesV1/request/serializer/ThreeDNodePropertiesFilterSerializer.java for this conversion activity.

I find it simpler to marter the objects.

2022-05-03 00:15 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +    }
I think it's good to have Enums, because if the DEVs try to add the information of the 3 objects at once? The API only accepts one object. In this case, we would have to validate field by fields and make an internal logic to know which fields belong to which objects. It would be more work and already with the enum the DEVs tell us which object it is trying to add in the destination.

2022-05-03 11:13 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  }
We cannot use the DataSourceType type as an enum for the type property, because for the RawDataSource object the type is "raw" and there is no enum equivalence for it.

2022-05-05 00:17 UTC, digaomilleniun commented on src/main/proto/transformation.proto
> +  message Owner {
Yes the API return object "owner". The API document is incorrect or not up to date.

2022-05-06 00:29 UTC, closed without merging

2022-05-06 00:30 UTC, digaomilleniun commented
I will open another PR with all code about transformations