Implement geolocation
cognitedata/cdf-sdk-java pull request #152
Opened 2022-05-03 16:00 UTC by pavelzubarev

2022-05-04 20:13 UTC, kjetilh33 requested changes

2022-05-04 20:13 UTC, kjetilh33 commented on src/main/proto/file.proto
> +
How about factoring the Geometry out to a separate (File independent) type/message? We may get that same feature (geo location) on other resource types in the future. 

Another thought: typing out the message a bit more? Something like this:
*
A Point is the basic geometry object. It represents a single coordinate point consisting of
longitude / latitude (or easting / northing) and an optional elevation.
 */
message Point {
    double lon = 1;
    double lat = 2;
    optional double elev = 3;
}

message MultiPoint {
    repeated Point coordinates = 1;
}

message LineString {
    repeated Point coordinates = 1;
}

message MultiLineString {
    repeated LineString coordinates = 1;
}

message Polygon {
    repeated LineString coordinates = 1;
}

message MultiPolygon {
    repeated Polygon coordinates = 1;
}

message Geometry {
    oneof geometry_type {
        Point point = 1;
        MultiPoint multi_point = 2;
        LineString line_string = 3;
        MultiLineString multi_line_string = 4;
        Polygon polygon = 5;
        MultiPolygon multi_polygon = 6;
    }
}

2022-05-04 20:13 UTC, kjetilh33 commented on src/main/proto/file.proto
> +    string type = 1;
Is the type field necessary? Isn't it given by the oneOf?

2022-05-04 20:13 UTC, kjetilh33 commented on src/main/proto/file.proto
> +    string type = 1;
Is the type field necessary? Isn't it given by the oneOf?

2022-05-04 20:20 UTC, kjetilh33 commented on src/main/proto/file.proto
> +    string type = 1;
Yes it is... (as I learned). But maybe it should be an enum rather than a string?

2022-05-04 20:32 UTC, kjetilh33 commented on src/main/proto/file.proto
> +
New suggestion, complete proto

syntax = "proto3";

package com.cognite.beam.proto;

import "google/protobuf/struct.proto";

option java_package = "com.cognite.client.dto";
option java_multiple_files = true;

/*
A Point is the basic geometry object. It represents a single coordinate point consisting of
longitude / latitude (or easting / northing) and an optional elevation.
 */
message Point {
    double lon = 1;
    double lat = 2;
    optional double elev = 3;
}

message MultiPoint {
    repeated Point coordinates = 1;
}

message LineString {
    repeated Point coordinates = 1;
}

message MultiLineString {
    repeated LineString coordinates = 1;
}

message Polygon {
    repeated LineString coordinates = 1;
}

message MultiPolygon {
    repeated Polygon coordinates = 1;
}

message Geometry {
    oneof geometry_type {
        Point point = 1;
        MultiPoint multi_point = 2;
        LineString line_string = 3;
        MultiLineString multi_line_string = 4;
        Polygon polygon = 5;
        MultiPolygon multi_polygon = 6;
    }
}

message Feature {
    Geometry geometry = 1;
    google.protobuf.Struct properties = 2;
}

2022-05-04 20:33 UTC, kjetilh33 commented on src/main/proto/file.proto
> +
Should we encapsulate all these geo-related types/messages by a common namespace?

2022-05-04 22:04 UTC, pavelzubarev commented on src/main/proto/file.proto
> +    string type = 1;
it did simplified the handling IMO, but it can be removed. Did remove

2022-05-04 22:09 UTC, pavelzubarev commented on src/main/proto/file.proto
> +
1. I'm not sure your definition complies to what API says. API says more than 2, but you want to make it 2 or 3, while api doesn't name fields in the way you propose.
2. I have not seen much of reuse of these definitions across other resources (maybe did not look carefully enough), so may call such refactoring a bit of premature optimisation. 
3. Point via array implementation does simplify serialisation, while handling fields separately will make code even more of cargo cult in my opinion. It's heavy already due to protobuf code generator nature,
4. Given that CDF API expects coordinates being ordered (it's an array), naming them in some way may confuse SDK users. I'm not sure going into lat/lon/elev is a right approach

2022-05-18 11:12 UTC, pavelzubarev commented
@kjetilh33 I've updated release.md as agreed

2022-05-19 10:56 UTC, kjetilh33 approved these changes

2022-05-19 11:02 UTC, merged