Add labels data set id
cognitedata/cdf-sdk-java pull request #71
Opened 2021-11-04 11:21 UTC by stigmarl-cognite

Add support in the SDK for the Labels resource to have a data set ID field

2021-11-04 11:22 UTC, pavelzubarev approved these changes
Have you checked both write and read?

2021-11-04 11:29 UTC, stigmarl-cognite commented
@kjetilh33 any suggestion on how to test this in a robust manner?

2021-11-05 08:43 UTC, kjetilh33 requested changes

2021-11-08 07:50 UTC, kjetilh33 approved these changes

2021-11-08 07:51 UTC, merged